### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections' 

### ISSUE THREAD

**Issue by don1uppa** [travistrle/export-dynamodb#18]
I'm using python 3.10 and installed all the requirements.
The program fails immediatly on the import error, here is the stack trace:

C:\dci\data_migration\venv\Scripts\python.exe C:/dci/data_migration/exportdynamodb/entrypoints/main.py --profile dev -t Carriers -f csv -o carriers.csv
Traceback (most recent call last):
  File "C:\dci\data_migration\exportdynamodb\entrypoints\main.py", line 7, in <module>
    from boto3 import Session
  File "C:\dci\data_migration\venv\lib\site-packages\boto3\__init__.py", line 16, in <module>
    from boto3.session import Session
  File "C:\dci\data_migration\venv\lib\site-packages\boto3\session.py", line 17, in <module>
    import botocore.session
  File "C:\dci\data_migration\venv\lib\site-packages\botocore\session.py", line 25, in <module>
    import botocore.configloader
  File "C:\dci\data_migration\venv\lib\site-packages\botocore\configloader.py", line 19, in <module>
    from botocore.compat import six
  File "C:\dci\data_migration\venv\lib\site-packages\botocore\compat.py", line 25, in <module>
    from botocore.exceptions import MD5UnavailableError
  File "C:\dci\data_migration\venv\lib\site-packages\botocore\exceptions.py", line 15, in <module>
    from botocore.vendored.requests.exceptions import ConnectionError
  File "C:\dci\data_migration\venv\lib\site-packages\botocore\vendored\requests\__init__.py", line 58, in <module>
    from . import utils
  File "C:\dci\data_migration\venv\lib\site-packages\botocore\vendored\requests\utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "C:\dci\data_migration\venv\lib\site-packages\botocore\vendored\requests\compat.py", line 7, in <module>
    from .packages import chardet
  File "C:\dci\data_migration\venv\lib\site-packages\botocore\vendored\requests\packages\__init__.py", line 3, in <module>
    from . import urllib3
  File "C:\dci\data_migration\venv\lib\site-packages\botocore\vendored\requests\packages\urllib3\__init__.py", line 10, in <module>
    from .connectionpool import (
  File "C:\dci\data_migration\venv\lib\site-packages\botocore\vendored\requests\packages\urllib3\connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "C:\dci\data_migration\venv\lib\site-packages\botocore\vendored\requests\packages\urllib3\response.py", line 9, in <module>
    from ._collections import HTTPHeaderDict
  File "C:\dci\data_migration\venv\lib\site-packages\botocore\vendored\requests\packages\urllib3\_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\diuppa\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)

Thoughts?

**Comment by don1uppa** [comment]
I did a search, I had success with Python 3.9.9. 

 make changes to main.py

Line 135: to eliminate blank lines in the output using windows
    with open(filename, 'w', newline='') as csvfile:

Line 140:
# Module level execution section
if __name__ == '__main__':
    main()
